apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      serviceAccountName: custom-scheduler-sa
      containers:
      - name: custom-scheduler
        image: neergasm/custom-scheduler:0.3  # Update the tag after rebuilding
        securityContext:
          runAsUser: 1001  # Matches the user in Dockerfile
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/kubernetes

  # apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: custom-scheduler
#   namespace: kube-system
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: custom-scheduler
#   template:
#     metadata:
#       labels:
#         app: custom-scheduler
#     spec:
#       serviceAccountName: custom-scheduler-sa  # 🔥 Use the created SA
#       containers:
#       - name: custom-scheduler
#         image: neergasm/custom-scheduler:0.2 
#         command:
#           - "/usr/bin/java"
#           - "-jar"
#           - "/app/k8s-scheduler.jar"
#         securityContext:
#           runAsNonRoot: true
#         resources:
#           limits:
#             cpu: "500m"
#             memory: "512Mi"
#           requests:
#             cpu: "250m"
#             memory: "256Mi"
#

