apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-service-account
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "bindings"]
    verbs: ["get", "list", "watch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduler-role
subjects:
  - kind: ServiceAccount
    name: scheduler-service-account
    namespace: kube-system



