apiVersion: v1
kind: Service
metadata:
  name: postgres-pod
spec:
  clusterIP: None  # Headless service
  selector:
    app: postgres-pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
